In [8]:
import numpy as np
#numpy is imported as its alias np
x=np.array([[1,2,3],[4,5,6]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(x)

numpy.ndarray

In [10]:
np.zeros(10)
#zeros function is used to pass 0 in a numpy array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#eye is used to represent identity matrix in python
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x.shape

(2, 3)

In [16]:
x[0,1]=5

In [17]:
x

array([[1, 5, 3],
       [4, 5, 6]])

In [18]:
x[1:4]

array([[4, 5, 6]])

In [19]:

x[:]

array([[1, 5, 3],
       [4, 5, 6]])

In [20]:
x[0]

array([1, 5, 3])

In [23]:
x[:,1:3]

#It means everything in columns 1 and 2


array([[5, 3],
       [5, 6]])

In [24]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [25]:
x.shape


(2, 3)